name: "Bug report"
description: "Something isn’t working as expected"
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) … 2) …"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Technitium 10.x; Proxmox 8.x; Debian 12 LXC"
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
